name: Tests

on: [push]

jobs:
  test-python-3_8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    services:
      rabbitmq:
        image: rabbitmq:3.13.7
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
            python-version: "3.8"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install . pytest pytest_asyncio
            

      - name: Run tests
        run: |
            pytest -s
    
  test-python-3_9:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    services:
      rabbitmq:
        image: rabbitmq:3.13.7
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
            python-version: "3.9"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install . pytest pytest_asyncio
            

      - name: Run tests
        run: |
            pytest -s

  test-python-3_10:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    services:
      rabbitmq:
        image: rabbitmq:3.13.7
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
            python-version: "3.10"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install . pytest pytest_asyncio
            

      - name: Run tests
        run: |
            pytest -s

  test-python-3_11:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    services:
      rabbitmq:
        image: rabbitmq:3.13.7
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
            python-version: "3.11"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install . pytest pytest_asyncio
            

      - name: Run tests
        run: |
            pytest -s

  test-python-3_12:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
      
      services:
        rabbitmq:
          image: rabbitmq:3.13.7
          env:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
          ports:
            - 5672:5672

      steps:
        - name: Git checkout
          uses: actions/checkout@v4
          
        - uses: actions/setup-python@v5
          with:
              python-version: "3.12"

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install . pytest pytest_asyncio
              

        - name: Run tests
          run: |
              pytest -s
      
